// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQbW0-IrfsTOACesKsuZdzH4CcCSqlf5I',
    appId: '1:151563051128:web:283b4ed513e0ee91368d8d',
    messagingSenderId: '151563051128',
    projectId: 'flutterdemo-9b236',
    authDomain: 'flutterdemo-9b236.firebaseapp.com',
    storageBucket: 'flutterdemo-9b236.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_c71Pk6u7F89fDYpA9zEk0Rj7jKPYF10',
    appId: '1:151563051128:android:9c621e7a4ffe6639368d8d',
    messagingSenderId: '151563051128',
    projectId: 'flutterdemo-9b236',
    storageBucket: 'flutterdemo-9b236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ9PT3SMs7Gy3C36SRLW99CTTbwdDn1ic',
    appId: '1:151563051128:ios:06eab7b327340e38368d8d',
    messagingSenderId: '151563051128',
    projectId: 'flutterdemo-9b236',
    storageBucket: 'flutterdemo-9b236.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ9PT3SMs7Gy3C36SRLW99CTTbwdDn1ic',
    appId: '1:151563051128:ios:06eab7b327340e38368d8d',
    messagingSenderId: '151563051128',
    projectId: 'flutterdemo-9b236',
    storageBucket: 'flutterdemo-9b236.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQbW0-IrfsTOACesKsuZdzH4CcCSqlf5I',
    appId: '1:151563051128:web:a0c50542122b1def368d8d',
    messagingSenderId: '151563051128',
    projectId: 'flutterdemo-9b236',
    authDomain: 'flutterdemo-9b236.firebaseapp.com',
    storageBucket: 'flutterdemo-9b236.firebasestorage.app',
  );
}
